apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: promote
  namespace: {{ .Values.application.environments.cicd }}
spec:
  params:
    - name: cluster
      description: cluster app url
      type: string
    - name: ref
      description: git ref
      type: string
    - name: repofullname
      type: string
    - name: revision
      description: git unique head commit id
      type: string
    - name: revision-short
      description: git unique head commit id short version
      type: string
    - name: revision-type
      description: revision type usually branch type
      type: string
    - name: revision-name
      description: revision name usually version or branch name
      type: string
    - name: author
      type: string
    - name: email
      type: string
  resources:
    inputs:
      - name: source
        type: git
      - name: image
        type: image
    outputs:
      - name: image
        type: image

  steps:
    - name: validate
      image: ubi8/nodejs-10
      resources: {}
      workingDir: /workspace/source
      script: |
        #!/bin/sh
        revisionType=$(params.revision-type)
        if [ "$revisionType" == "release" ] || [ "$revisionType" = "hotfix" ] || [ "$revisionType" = "patch" ]; then
          exit 0
        else
          echo "Preventing $revisionType to be promoted to a production environment"
          exit 1
        fi

    - name: release-notes
      image: ubi8/nodejs-10
      workingDir: /workspace/source/{{ .Values.pipeline.build.context }}
      volumeMounts:
        - name: {{ .Values.pipeline.webhook.github.key }}
          mountPath: /etc/idrsa
          readOnly: true
      script: |
        #!/bin/sh
        before=$(cat package.json \
        | grep version \
        | head -1 \
        | awk -F: '{ print $2 }' \
        | sed 's/[",]//g')        
        before=$(echo -e $before)

        ls -ls /etc/idrsa/
        touch ~/.ssh/config
        ssh-add /etc/idrsa/ssh-privatekey
        # chmod 400 ~/.ssh/id_rsa
        chmod 600 ~/.ssh/config
        tee -a ~/.ssh/config << END
        host github.com
          HostName github.com
          IdentitiesOnly yes
          IdentityFile /etc/idrsa/ssh-privatekey
          User git
        END
        ssh-keyscan github.com >> ~/.ssh/known_hosts

        git config --global user.name  "$(params.author)"
        git config --global user.email "$(params.email)"
        git remote set-url origin "git@github.com:{{ .Values.pipeline.webhook.github.org }}/{{ .Values.pipeline.webhook.github.repo }}.git"

        git fetch --all --tags > /dev/null 2>&1
        git checkout -b $(params.revision-type)/$(params.revision-name) > /dev/null 2>&1
        git log master..$(params.revision-type)/$(params.revision-name) --oneline --no-merges --decorate > release-v$(params.revision-name).md > /dev/null 2>&1
        
        # hack for first version to be upgraded as major
        if [ "$before" == "0.0.0" ]; then
          npm version major > /dev/null 2>&1
        else
          npm version minor > /dev/null 2>&1
        fi

        git add release-v$(params.revision-name).md
        git add package.json
        git commit -m "Including release notes"
        git tag -a $(params.revision-name) -m "Upgrade to v$(params.revision-name)"
        git push origin $(params.revision-type)/$(params.revision-name) --tags

    - name: release-image
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      script: |
        #!/bin/sh
        replace=$(inputs.params.revision-name)
        revisionName=${replace//./-}
        appname={{ .Values.application.name }}-$(inputs.params.revision-type)-$revisionName
        oc tag {{ .Values.application.environments.development }}/{{ .Values.application.name }}-development:$(inputs.params.revision-name) {{ .Values.application.environments.production }}/{{ .Values.application.name }}-production:$(inputs.params.revision-name)
        oc tag {{ .Values.application.environments.production }}/{{ .Values.application.name }}-production:$(inputs.params.revision-name) {{ .Values.application.environments.production }}/{{ .Values.application.name }}-production:$(inputs.params.revision-name)
        oc get deployment/$appname -n {{ .Values.application.environments.production }}
        if [[ $? -ne 0 ]]
        then
            oc new-app --name=$appname -i={{ .Values.application.name }}-production:$(inputs.params.revision-name) --namespace={{ .Values.application.environments.production }} --labels=app.name={{ .Values.application.name }}
        else
            echo "Application already exists."
        fi

    - name: app-expose
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      script: |
        #!/bin/sh
        replace=$(inputs.params.revision-name)
        revisionName=${replace//./-}
        hostname=v$revisionName-{{ .Values.application.environments.production }}.{{ .Values.cluster }}
        appname={{ .Values.application.name }}-$(inputs.params.revision-type)-$revisionName
        
        sleep 10
        oc get svc/$appname -n {{ .Values.application.environments.production }}
        if [[ $? -ne 0 ]]; then
          echo "Exposing"
          oc expose svc/$appname -n {{ .Values.application.environments.production }}
        else
          echo "Application is already exposed."
          echo $hostname
        fi

        sleep 10
        
        oc get route/$appname -n {{ .Values.application.environments.production }}
        if [[ $? -ne 0 ]]; then
          echo "Creating routes"
          oc create route edge --service $appname --port 8080 --hostname $hostname -n {{ .Values.application.environments.production }}
          sleep 5
          oc patch svc/$appname -p '{ "spec": {"type":"LoadBalancer"}}, { "ports": [ { "name": "gw", "protocol": "TCP", "port": 8080,"targetPort": 8080 } ] } }' -n {{ .Values.application.environments.production }}
          # oc expose svc/nodejs-tekton-release-1-2-0 -n nodejs-tekton-production
        else
          echo "Route is already available."
          echo $hostname
        fi

    - name: app-labels
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      script: |
        #!/bin/sh
        replace=$(inputs.params.revision-name)
        revisionName=${replace//./-}
        appname={{ .Values.application.name }}-$(inputs.params.revision-type)-$revisionName
        environment={{ .Values.application.environments.production }}
        oc label deployment/$appname --overwrite app.kubernetes.io/name=$appname -n $environment
        oc label deployment/$appname --overwrite app.version=$revisionName -n $environment
        oc label deployment/$appname --overwrite app.revision-id=$(inputs.params.revision-short) -n $environment
        oc label deployment/$appname --overwrite app.revision-type=$(inputs.params.revision-type) -n $environment
        oc label deployment/$appname --overwrite app.revision-name=$revisionName -n $environment
        oc label deployment/$appname --overwrite app.revision-author=$(inputs.params.author) -n $environment

    - name: app-envs
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      script: |
        #!/bin/sh
        replace=$(inputs.params.revision-name)
        revisionName=${replace//./-}
        appname={{ .Values.application.name }}-$(inputs.params.revision-type)-$revisionName
        environment={{ .Values.application.environments.production }}
        oc set env deployment/$appname --list -n $environment
        oc set env deployment/$appname --overwrite environment=production -n $environment
        oc set env deployment/$appname --overwrite version=$(inputs.params.revision-name) -n $environment
        oc set env deployment/$appname --overwrite revision-id=$(inputs.params.revision-short) -n $environment
        oc set env deployment/$appname --overwrite revision-name=$revisionName -n $environment
        oc set env deployment/$appname --overwrite revision-type=$(inputs.params.revision-type) -n $environment

    - name: app-secrets
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          replace=$(inputs.params.revision-name)
          revisionName=${replace//./-}
          appname={{ .Values.application.name }}-$(inputs.params.revision-type)-$revisionName
          # example
          # oc set env deployment/$appname --from secret/input -n {{ .Values.application.environments.production }}

    - name: app-probes
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          replace=$(inputs.params.revision-name)
          revisionName=${replace//./-}
          appname={{ .Values.application.name }}-$(inputs.params.revision-type)-$revisionName
          oc set probe deployment/$appname --remove --readiness --liveness -n {{ .Values.application.environments.production }}
          oc set probe deployment/$appname --readiness --get-url=http://:8080/ --initial-delay-seconds=30 -n {{ .Values.application.environments.production }}

    - name: app-autoscale
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      script: |
        #!/bin/sh

        replace=$(inputs.params.revision-name)
        revisionName=${replace//./-}

        if [ "$(inputs.params.revision-type)" == "release" ] || [ "$(inputs.params.revision-type)" == "hotfix" ] || [ "$(inputs.params.revision-type)" == "patch" ]; then
          appname={{ .Values.application.name }}-$(inputs.params.revision-type)-$revisionName
          min=1
          max=10
          threshold=50

          oc get hpa $appname -n {{ .Values.application.environments.production }} --ignore-not-found
          if [[ $? -ne 0 ]]; then
            oc autoscale deployment $appname \
              --min $min --max $max --cpu-percent=$threshold \
              --namespace {{ .Values.application.environments.production }}
          else
            echo "Application autoscale is already configured."
          fi
        fi

    - name: app-triggers
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          replace=$(inputs.params.revision-name)
          revisionName=${replace//./-}
          appname={{ .Values.application.name }}-$(inputs.params.revision-type)-$revisionName
          oc set triggers deployment/$appname -n {{ .Values.application.environments.production }}

    - name: pull-request
      image: ubi8/nodejs-10
      resources: {}
      workingDir: /workspace/source
      script: |
        #!/bin/sh
        curl -s https://api.github.com/repos/github/hub/releases/latest | grep browser_download_url | grep linux-amd64 | cut -d '"' -f 4 | wget -qi -
        tar -xzf "$(find . -name "*hub-linux-amd64*")"
        folder="$(find . -name "*hub-linux-amd64*" -type d)"
        folder=${folder//.\//}
        chmod +x $folder/bin/hub
        tee -a template.md << END
          ### v$(inputs.params.revision-name)
          This is a template
        END

        $folder/bin/hub pull-request \
          --message="v$(inputs.params.revision-name)" \
          --labels=release \
          --file - < template.md \
          --base={{ .Values.pipeline.webhook.github.org }}:master \
          --head={{ .Values.pipeline.webhook.github.org }}:$(inputs.params.revision-type)/$(inputs.params.revision-name)
      env:
        - name: GITHUB_USER
          value: {{ .Values.pipeline.webhook.github.user }}
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.pipeline.webhook.github.secret }}
              key: token

    - name: report
      image: registry.access.redhat.com/ubi8/ubi:latest
      workingDir: /workspace/source
      env:
        - name: GITHUBTOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.pipeline.webhook.github.secret }}
              key: token
      script: |
        #!/usr/libexec/platform-python
        import json
        import os
        import http.client
        status_url = """/repos/$(params.repofullname)/statuses/$(params.revision)"""

        data = {
            "state": "success",
            "target_url": "https://replaceme",
            "description": "Building",
            "context": "tekton"
        }
        conn = http.client.HTTPSConnection("api.github.com")
        r = conn.request(
            "POST",
            status_url.rstrip("\n"),
            body=json.dumps(data),
            headers={
                "User-Agent": "TektonCD, the peaceful cat",
                "Authorization": "Bearer " + os.environ["GITHUBTOKEN"],
            })
        resp = conn.getresponse()
        if not str(resp.status).startswith("2"):
            print("Error: %d" % (resp.status))
            print(resp.read())
            # sys.exit(resp.read())
        else:
          print("GitHub status 'pending' has been set")

  volumes:
    - name: {{ .Values.pipeline.webhook.github.key }}
      secret:
        secretName: {{ .Values.pipeline.webhook.github.key }}