apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: standards
  namespace: {{ .Values.application.environments.cicd }}
spec:
  workspaces:
  - name: shared
  params:
    - name: ref
      description: Git reference
    - name: repourl
      description: repository url from github payload
    - name: repofullname
      description: full name user-org/reponame from github
    - name: revision
      description: commit head unique id
      type: string
    - name: revision-type
      description: revision type
      type: string
    - name: revision-name
      description: revision name
      type: string
  steps:
    - name: code-prepare
      image: registry.access.redhat.com/ubi8/nodejs-10
      workingDir: /workspace/shared/{{ .Values.pipeline.build.context }}
      script: |
        #!/bin/sh
        npm ping --registry {{ .Values.pipeline.nexus.host }}
        if [[ $? -ne 0 ]]; then
          npm install --only-dev --unsafe-perm=true --allow-root
        else
          echo Using nexus
          npm --registry {{ .Values.pipeline.nexus.host }} install --only-dev --unsafe-perm=true --allow-root
        fi
      securityContext:
        runAsUser: 0

    # - name: code-audit
    #   image: ubi8/nodejs-10
    #   resources: {}
    #   workingDir: /workspace/shared/{{ .Values.pipeline.build.context }}
    #   command: ["/bin/bash", "-c"]
    #   args:
    #     - |-
    #       npm audit
    #   securityContext:
    #     runAsUser: 0

    - name: code-lint
      image: quay.io/redhat-cop/uncontained-local-dev
      resources: {}
      workingDir: /workspace/shared/{{ .Values.pipeline.build.context }}
      command: ["/bin/bash", "-c"]
      args:
        - |-
          npm run lint
      securityContext:
        runAsUser: 0

    # - name: code-coverage
    #   image: quay.io/redhat-cop/uncontained-local-dev
    #   resources: {}
    #   workingDir: /workspace/shared/{{ .Values.pipeline.build.context }}
    #   script: |
    #     #!/bin/sh
    #     npm run coverage

  volumes:
    - name: varlibcontainers
      emptyDir: {}
    - name: gen-source
      emptyDir: {}