apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.environments.cicd }}
  labels:
    app: {{ .Values.application.name }}
spec:
  workspaces:
    - name: {{ .Values.application.name }}-shared
  resources:
    - name: {{ .Values.application.name }}-git
      type: git
    - name: {{ .Values.application.name }}-development
      type: image
    - name: {{ .Values.application.name }}-production
      type: image
    - name: {{ .Values.application.name }}-documentation
      type: image
    
  params:
    - name: ref
      description: ref of the application
    - name: revision
      description: git unique head commit id
    - name: repourl
      description: repository full name
    - name: repofullname
      description: repository full name
    - name: author
      description: commit author username
    - name: email
      description: commit author email
    - name: message
      description: commit message

  tasks:
    - name: info
      taskRef:
        kind: Task
        name: status
      resources:       
        inputs:
          - name: source
            resource: {{ .Values.application.name }}-git
      workspaces:
        - name: shared
          workspace: {{ .Values.application.name }}-shared
      params:
      - name: ref
        value: $(params.ref)
      - name: repourl
        value: $(params.repourl)
      - name: repofullname
        value: $(params.repofullname)
      - name: revision
        value: $(params.revision)
      - name: author
        value: $(params.author)
      - name: message
        value: $(params.message)

    - name: standards
      taskRef:
        name: standards
      runAfter:
        - info
      workspaces:
        - name: shared
          workspace: {{ .Values.application.name }}-shared
      params:
        - name: ref
          value: $(tasks.info.results.ref)
        - name: repourl
          value: $(params.repourl)
        - name: repofullname
          value: $(params.repofullname)
        - name: revision
          value: $(tasks.info.results.revision)
        - name: revision-type
          value: $(tasks.info.results.revision-type)
        - name: revision-name
          value: $(tasks.info.results.revision-name)

    - name: build
      taskRef:
        name: build
      workspaces:
        - name: shared
          workspace: {{ .Values.application.name }}-shared
      runAfter:
        - standards
      params:
        - name: ref
          value: $(tasks.info.results.ref)
        - name: repourl
          value: $(params.repourl)
        - name: repofullname
          value: $(params.repofullname)
        - name: revision
          value: $(tasks.info.results.revision)
        - name: revision-type
          value: $(tasks.info.results.revision-type)
        - name: revision-name
          value: $(tasks.info.results.revision-name)
        - name: author
          value: $(tasks.info.results.author)
      resources:
        outputs:
          - name: image
            resource: {{ .Values.application.name }}-development
          - name: documentation
            resource: {{ .Values.application.name }}-documentation

    - name: docs
      taskRef:
        name: docs
      runAfter:
        - build
      workspaces:
        - name: shared
          workspace: {{ .Values.application.name }}-shared
      params:
        - name: ref
          value: $(tasks.info.results.ref)
        - name: repourl
          value: $(params.repourl)
        - name: repofullname
          value: $(params.repofullname)
        - name: revision
          value: $(tasks.info.results.revision)
        - name: revision-type
          value: $(tasks.info.results.revision-type)
        - name: revision-name
          value: $(tasks.info.results.revision-name)
        - name: author
          value: $(tasks.info.results.author)
      resources:       
        outputs:
          - name: documentation
            resource: {{ .Values.application.name }}-documentation

    - name: deploy
      taskRef:
        name: deploy
      runAfter:
        - docs
      params:
        - name: cluster
          value: $(tasks.info.results.cluster)
        - name: ref
          value: $(tasks.info.results.ref)
        - name: revision
          value: $(tasks.info.results.revision)
        - name: revision-short
          value: $(tasks.info.results.revision-short)
        - name: revision-type
          value: $(tasks.info.results.revision-type)
        - name: revision-name
          value: $(tasks.info.results.revision-name)
        - name: author
          value: $(tasks.info.results.author)
      resources:
        inputs:
          - name: image
            resource: {{ .Values.application.name }}-development

    - name: test-e2e
      taskRef:
        name: test-integration
      workspaces:
        - name: shared
          workspace: {{ .Values.application.name }}-shared
      runAfter:
        - deploy
      params:
      - name: ref
        value: $(params.ref)
      - name: repourl
        value: $(params.repourl)
      - name: repofullname
        value: $(params.repofullname)
      - name: revision
        value: $(params.revision)
      - name: revision-type
        value: $(tasks.info.results.revision-type)
      - name: revision-name
        value: $(tasks.info.results.revision-name)

    - name: promote
      # conditions:
      #   - conditionRef: is-allowed-production
      #     params:
      #       - name: revision-type
      #         value: $(tasks.info.results.revision-type)
      taskRef:
        name: promote
      runAfter:
        - test-e2e
      params:
      - name: cluster
        value: $(tasks.info.results.cluster)
      - name: repofullname
        value: $(params.repofullname)
      - name: ref
        value: $(tasks.info.results.ref)
      - name: revision
        value: $(tasks.info.results.revision)
      - name: revision-short
        value: $(tasks.info.results.revision-short)
      - name: revision-type
        value: $(tasks.info.results.revision-type)
      - name: revision-name
        value: $(tasks.info.results.revision-name)
      - name: author
        value: $(params.author)
      - name: email
        value: $(params.email)
      resources:
        inputs:
          - name: source
            resource: {{ .Values.application.name }}-git
          - name: image
            resource: {{ .Values.application.name }}-development
        outputs:
          - name: image
            resource: {{ .Values.application.name }}-production

    - name: release
      taskRef:
        kind: Task
        name: tag
      runAfter:
        - promote
      params:
      - name: author
        value: $(params.author)
      - name: email
        value: $(params.email)
      - name: revision-type
        value: $(tasks.info.results.revision-type)
      - name: revision-name
        value: $(tasks.info.results.revision-name)
      resources:
        inputs:
          - name: source
            resource: {{ .Values.application.name }}-git